version: '3.9'
services:
  unifi-controller:
    container_name: Unifi-Controller
    image: linuxserver/unifi-controller:latest
    restart: always
    hostname: SHUC01
    network_mode: bridge
    ports:
      - 10001:10001/udp
      - 1900:1900/udp
      - 3478:3478/udp
      - 5514:5514
      - 6789:6789
      - 8080:8080
      - 8443:8443
      - 8843:8843
      - 8880:8880
    environment:
      TZ: America/Edmonton
      PUID: 1000
      PGID: 100
    volumes:
      - /srv/dev-disk-by-label-ServerHDD/Docker/Unifi Controller:/config
