version: '3.9'
services:
  sonarr:
    container_name: Sonarr
    image: linuxserver/sonarr:latest
    restart: always
    hostname: SHSNR01
    network_mode: bridge
    ports:
      - 8989:8989
    environment:
      TZ: America/Edmonton
      PUID: 1000
      PGID: 100
    volumes:
      - /srv/dev-disk-by-label-DATA/Docker/Sonarr:/config
      - /srv/dev-disk-by-label-DATA/Share/Torrents:/downloads
      - /srv/dev-disk-by-label-DATA/Share/TV Shows:/tv
