version: '3.9'
services:
  homebridge:
    container_name: Homebridge
    image: oznu/homebridge:latest
    network_mode: host
    environment:
      TZ: America/Edmonton
      PUID: 1000
      PGID: 100
      HOMEBRIDGE_CONFIG_UI: 1
      HOMEBRIDGE_CONFIG_UI_PORT: 8090
    volumes:
      - /srv/dev-disk-by-label-DATA/Docker/Homebridge:/homebridge
