version: '3.9'
services:
  heimdall:
    container_name: Heimdall
    image: linuxserver/heimdall:latest
    restart: always
    hostname: SHHMDL01
    network_mode: bridge
    ports:
      - 7443:443
      - 7080:80
    environment:
      TZ: America/Edmonton
      PUID: 1000
      PGID: 100
    volumes:
      - /srv/dev-disk-by-label-ServerHDD/Docker/Heimdall:/config
